#!/usr/bin/env python3
"""Refresh the clean project structure summary.

Run this after any preprocessing, splitting, or training step. It also keeps all
Markdown summaries inside markdown_reports/ so reports stay easy to review.
"""

from __future__ import annotations

import shutil
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
MARKDOWN_DIR = PROJECT_ROOT / 'markdown_reports'
IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.bmp', '.webp'}
PROJECT_MARKDOWN_SOURCES = ['reports', 'notebooks', 'scripts', 'src']
IGNORED_DIRS = {'.venv', '__pycache__', '.ipynb_checkpoints'}


def count_images(folder: Path) -> int:
    if not folder.exists():
        return 0
    return sum(
        1
        for path in folder.rglob('*')
        if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS
    )


def count_symlinks(folder: Path) -> int:
    if not folder.exists():
        return 0
    return sum(1 for path in folder.rglob('*') if path.is_symlink())


def safe_markdown_name(path: Path) -> str:
    """Avoid overwriting when two reports have the same markdown filename."""
    candidate = path.name
    target = MARKDOWN_DIR / candidate
    if not target.exists() or target.resolve() == path.resolve():
        return candidate
    parent = path.parent.name
    candidate = f'{parent}_{path.name}'
    counter = 2
    while (MARKDOWN_DIR / candidate).exists():
        candidate = f'{parent}_{path.stem}_{counter}{path.suffix}'
        counter += 1
    return candidate


def collect_markdown_reports() -> list[str]:
    MARKDOWN_DIR.mkdir(parents=True, exist_ok=True)
    moved: list[str] = []
    for source in PROJECT_MARKDOWN_SOURCES:
        source_root = PROJECT_ROOT / source
        if not source_root.exists():
            continue
        for path in sorted(source_root.rglob('*.md')):
            if MARKDOWN_DIR in path.parents:
                continue
            if any(part in IGNORED_DIRS for part in path.parts):
                continue
            if path.name.startswith('.'):
                continue
            target = MARKDOWN_DIR / safe_markdown_name(path)
            if target.exists():
                target.unlink()
            shutil.move(str(path), str(target))
            moved.append(str(target.relative_to(PROJECT_ROOT)))
    return moved


def class_counts() -> list[tuple[str, int]]:
    images_root = PROJECT_ROOT / 'data' / 'selected_images'
    if not images_root.exists():
        return []
    rows = []
    for class_dir in sorted(path for path in images_root.iterdir() if path.is_dir()):
        rows.append((class_dir.name, count_images(class_dir)))
    return rows


def split_counts() -> list[tuple[str, int, int]]:
    split_root = PROJECT_ROOT / 'data' / 'splits'
    rows = []
    for split in ['train', 'val', 'test']:
        folder = split_root / split
        rows.append((split, count_symlinks(folder), count_images(folder)))
    return rows


def list_markdown_reports() -> list[str]:
    if not MARKDOWN_DIR.exists():
        return []
    return sorted(path.name for path in MARKDOWN_DIR.glob('*.md'))


def write_structure() -> None:
    collect_markdown_reports()

    selected_total = count_images(PROJECT_ROOT / 'data' / 'selected_images')
    selected_classes = len(class_counts())
    quarantine_total = count_images(PROJECT_ROOT / 'data' / 'quarantine_quality')
    split_rows = split_counts()
    split_total = sum(row[1] for row in split_rows)
    markdown_files = list_markdown_reports()
    updated_at = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')

    lines = [
        'combine_skindiseaseclassifier_devraj',
        'Auto-generated by scripts/update_project_structure.py',
        f'Last updated: {updated_at}',
        '',
        'Main Folder Structure',
        '├── data',
        f'│   ├── selected_images        # final selected dataset: {selected_classes} classes, {selected_total:,} images',
        f'│   ├── splits                 # train/val/test symlink split: {split_total:,} linked images',
        f'│   └── quarantine_quality     # quality-failed images kept out of training: {quarantine_total:,} files',
        '├── reports                   # CSV/JSON reports by process',
        '│   ├── label_mapping',
        '│   ├── manifests',
        '│   ├── perceptual_hash',
        '│   ├── quality',
        '│   └── split',
        f'├── markdown_reports          # all readable .md summaries: {len(markdown_files)} files',
        '├── notebooks                 # step-wise notebooks for mentor-visible outputs',
        '├── src                       # reusable PyTorch/model/training code',
        '├── scripts                   # runnable pipeline scripts',
        '└── training_outputs          # future model outputs/checkpoints/results',
        '',
        'Important Paths',
        f'- Dataset images: {PROJECT_ROOT / "data" / "selected_images"}',
        f'- Train/val/test split: {PROJECT_ROOT / "data" / "splits"}',
        f'- Markdown summaries: {PROJECT_ROOT / "markdown_reports"}',
        f'- Process reports: {PROJECT_ROOT / "reports"}',
        f'- Notebooks: {PROJECT_ROOT / "notebooks"}',
        f'- Source code: {PROJECT_ROOT / "src"}',
        f'- Scripts: {PROJECT_ROOT / "scripts"}',
        f'- Training outputs: {PROJECT_ROOT / "training_outputs"}',
        '',
        'Selected Class Counts',
    ]

    for class_name, count in class_counts():
        lines.append(f'- {class_name}: {count:,}')

    lines.extend(['', 'Split Counts'])
    for split, links, files in split_rows:
        count_text = f'{links:,} symlinks'
        if files and files != links:
            count_text += f', {files:,} real files'
        lines.append(f'- {split}: {count_text}')

    lines.extend(['', 'Markdown Reports'])
    if markdown_files:
        for filename in markdown_files:
            lines.append(f'- markdown_reports/{filename}')
    else:
        lines.append('- No markdown reports found yet.')

    lines.extend([
        '',
        'Rule Going Forward',
        '- After any preprocessing, splitting, or training step, run:',
        '  python3 scripts/update_project_structure.py',
        '- New markdown reports should be kept in markdown_reports/. This script moves them there automatically.',
    ])

    (PROJECT_ROOT / 'PROJECT_STRUCTURE.txt').write_text('\n'.join(lines) + '\n', encoding='utf-8')


def main() -> None:
    write_structure()
    print(f'Updated: {PROJECT_ROOT / "PROJECT_STRUCTURE.txt"}')


if __name__ == '__main__':
    main()
